-- Answer 1 : 1-n
-- Answer 2: 
SELECT NAME.STUDENT,
	   GENDER.STUDENT,
	   NAME
	FROM CLASS C
	  JOIN STUDENT S
	  	ON C.ID = S.ID;
-- Answer 3:
SELECT TEACHER,
	   COUNT(GENDER)
	FROM CLASS C
	  JOIN STUDENT S
	    ON C.ID = S.ID
	WHERE NAME.CLASS = '12A'
	AND GENDER = 'MALE';
-- Answer 4:
SELECT NAME.STUDENT,
	   SCORE.RESULT
	FROM STUDENT S
	  JOIN RESULT R
	    ON S.ID = R.ID
	  JOIN CLASS C
	  	ON C.ID = R.ID
	WHERE NAME.CLASS = '12B';
	
	
