CREATE DATABASE JAVA16_INTERN_TEST CHAR SET utf8mb4;
USE JAVA16_INTERN_TEST;

CREATE TABLE CLASS
(
ID INT,
`NAME` VARCHAR(50) NOT NULL,
TEACHER VARCHAR(50) NOT NULL,
CONSTRAINT PK_CLASS PRIMARY KEY (ID)
);
CREATE TABLE STUDENT
(
ID INT,
`NAME` VARCHAR(50) NOT NULL,
GENDER VARCHAR(50) NOT NULL,
CLASS_ID INT,
CONSTRAINT PK_STUDENT PRIMARY KEY(ID),
CONSTRAINT FK_STUDENT_CALSS FOREIGN KEY(CLASS_ID) REFERENCES CLASS(ID)
);
CREATE TABLE RESULT
(
STUDENT_ID INT,
`SUBJECT` VARCHAR(50) NOT NULL,
SCORE INT,
CONSTRAINT PK_RESULT PRIMARY KEY(SCORE),
CONSTRAINT FK_RESULT_STUDENT FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID)

);
SELECT name, gender, 
(SELECT name 
FROM Class WHERE id = Student.class_id)AS class_name
FROM Student;

-- Answer 3
SELECT Class.teacher,COUNT(Student.id) as "number of female student" 
FROM Student 
JOIN Class ON Student.classid = Class.id
WHERE Student.gender = "female" AND Student.classid = (SELECT ID FROM Class WHERE Class.name = "12B")
GROUP BY Class.ID;