CREATE DATABASE SCHOOL CHAR SET utf8mb4;
USE SCHOOL;

CREATE TABLE CLASS(
 ID INT PRIMARY KEY,
 `NAME` VARCHAR(50) NOT NULL,
 TEACHER VARCHAR(50) NOT NULL
);

CREATE TABLE STUDENT(
 ID INT PRIMARY KEY,
 `NAME` VARCHAR(50) NOT NULL,
 GENDER VARCHAR(50) NOT NULL,
 CLASS_ID INT,
 FOREIGN KEY (CLASS_ID) REFERENCES CLASS(ID)
);

CREATE TABLE RESULT(
  STUDENT_ID INT PRIMARY KEY,
  `SUBJECT` VARCHAR(50) NOT NULL,
  SCORE INT NOT NULL,
  FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(ID)
);

INSERT INTO CLASS(ID, `NAME`, TEACHER)
VALUES(1, '12A', 'Ho Cong Trung'),
(2, '12B', 'Dang Tu Anh'),
(3, '12C', 'Nguyen Van Tam');

INSERT INTO STUDENT(ID, `NAME`, GENDER, CLASS_ID)
VALUES(1, 'Dinh Thi Ngoc', 'Female', 2),
(2, 'Nguyen Thanh Hung', 'Male', 1),
(3, 'Tran Mai Hoa', 'Female', 2),
(4, 'Doan Quang Vinh', 'Male', 1),
(5, 'Cao Anh Dao', 'Female', 3),
(6, 'Tran Kim Tuyen', 'Male', 3);

INSERT INTO RESULT(STUDENT_ID, `SUBJECT`, SCORE)
VALUES(1, 'Math', 9),
(2, 'Math', 8),
(3, 'Math', 3),
(4, 'Math', 2),
(5, 'Math', 4),
(6, 'Math', 9);

SELECT STUDENT.`NAME`, STUDENT.GENDER, CLASS.`NAME`
FROM STUDENT
JOIN CLASS
ON STUDENT.CLASS_ID = CLASS.ID;

SELECT CLASS.TEACHER, COUNT(STUDENT.ID) AS so_hs_nam
FROM CLASS
JOIN STUDENT
ON CLASS.ID = STUDENT.CLASS_ID
WHERE CLASS.`NAME` = '12A' AND STUDENT.GENDER = 'Male'
GROUP BY CLASS.TEACHER;


