CREATE DATABASE JAVA16_FINAL_TEST;
CREATE TABLE KHACHHANG(
	MAKH VARCHAR(50) PRIMARY KEY,
    TENKH VARCHAR(50) NOT NULL,
    DIACHI VARCHAR(50) NOT NULL,
    SODT VARCHAR(10) NOT NULL,
    MASOTHUE VARCHAR(20) NOT NULL
);

CREATE TABLE PHONG(
	MAPHONG VARCHAR(50) PRIMARY KEY,
    SOKHACHTOIDA INT NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL,
    MOTA VARCHAR(100) NOT NULL
);

CREATE TABLE MUCTIENGIO(
	MATIENGIO VARCHAR(50) PRIMARY KEY,
    DONGIA INT NOT NULL,
    MOTA VARCHAR(100) NOT NULL
);


CREATE TABLE HOADON(
	MAHD VARCHAR(50) PRIMARY KEY,
    MAKH VARCHAR(50),
    MAPHONG VARCHAR(50),
    MATIENGIO VARCHAR(50),
    THOIGIANBATDAUSD DATETIME NOT NULL,
    THOIGIANKETTHUCSD DATETIME NOT NULL,
    TRANGTHAIHD VARCHAR(50) NOT NULL,
    CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_MAPHONG FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_MATIENGIO FOREIGN KEY(MATIENGIO) REFERENCES MUCTIENGIO(MATIENGIO)
);

CREATE TABLE DICHVU(
	MADV VARCHAR(50) PRIMARY KEY,
    TENDV VARCHAR(50) NOT NULL,
    DONVITNH VARCHAR(50) NOT NULL,
    DONGIA INT NOT NULL
);

CREATE TABLE CHITIET_SUDUNGDV(
	MAHD VARCHAR(50),
    MADV VARCHAR(50), 
    SOLUONG INT NOT NULL,
    PRIMARY KEY(MAHD, MADV),
	CONSTRAINT FK_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
    CONSTRAINT FK_MADV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV)
);

-- Chèn dữ liệu mẫu cho bảng KHACHHANG
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,SODT,MASOTHUE)
VALUES   ('KH001', 'Tran Van Nam', 'Hai Chau', '0123456789', '1234567890'),
    ('KH002', 'Nguyen Mai Anh', 'Lien Chieu', '0987654321', '0987654321'),
    ('KH003', 'Pham Hoai Lan Khue', 'Hoa Vang', '0123987654', '1112223334'),
    ('KH004', 'Nguyen Hoai Nguyen', 'Hoa Cam', '0909090909', '5556667778');
 
 -- Chèn dữ liệu mẫu cho bảng PHONG
INSERT INTO PHONG(MAPHONG,SOKHACHTOIDA,TRANGTHAI,MOTA)
VALUES  ('VIP01', 5, 'Duoc su dung', 'phong vip'),
    ('P02', 10, 'Duoc su dung', 'phong binh thuong'),
    ('P03', 15, 'Duoc su dung', 'phong binh thuong'),
    ('VIP04', 20, 'Duoc su dung', 'phong vip');

-- Chèn dữ liệu mẫu cho bảng DICHVU       
INSERT INTO DICHVU(MADV,TENDV,DONVITNH,DONGIA)
VALUES     ('DV01', 'Hat Dua', 'Bao', 5000),
    ('DV02', 'Trai cay', 'Dia', 30000),
    ('DV03', 'Bia', 'Lon', 35000),
    ('DV04', 'Nuoc Ngot', 'Chai', 10000);

-- Chèn dữ liệu mẫu cho bảng MUCTIENGIO
INSERT INTO MUCTIENGIO(MATIENGIO,DONGIA,MOTA)
VALUES ('MT01', 60000, 'Ap dung tu 6 gio den 17 gio'),
       ('MT02', 80000, 'Ap dung sau 17 gio den 22 gio');

-- Chèn dữ liệu mẫu cho bảng HOADON
INSERT INTO HOADON()
VALUES ('HD001', 'KH01', 'VIP01', 'MT01', current_timestamp(), current_timestamp(), 'Da thanh toan'),
       ('HD002', 'KH02', 'P02', 'MT01', current_timestamp(), current_timestamp(), 'Chua thanh toan');
       
INSERT INTO CHITIET_SUDUNGDV(MAHD,MADV,SOLUONG)
VALUES ('HD001', 'DV01', 5),
       ('HD002', 'DV01', 8);
       
-- 3. Liệt kê các phòng karaoke được sử dụng nhiều nhất từ 02.2014 đến 02.2015
SELECT p.MAPHONG, hd.THOIGIANBATDAUSD, hd.THOIGIANKETTHUCSD 
FROM PHONG p
JOIN HOADON hd
ON p.MAPHONG = hd.MAPHONG
WHERE  CAST(THOIGIANBATDAUSD AS DATE) BETWEEN STR_TO_DATE('02/2014', '%m/%Y') AND STR_TO_DATE('02/2015', '%m/%Y');

-- 4. Liệt kê 2 dịch vụ được sử dụng nhiều nhất trong mỗi tháng từ 01.2014 đến 12.2014
SELECT dv. MADV, dv.TENDV
FROM DICHVU dv
JOIN CHITIET_SUDUNGDV ctdv
ON dv.MADV = ctdv.MADV
JOIN HOADON hd
ON hd.MAHD = ctdv.MAHD
WHERE CAST(hd.THOIGIANBATDAUSD AS DATE) BETWEEN STR_TO_DATE('10/2015', '%m/%Y') AND STR_TO_DATE('01/2016', '%m/%Y')
GROUP BY (dv.MADV)
ORDER BY COUNT(dv.MADV) DESC
LIMIT 2;

-- 5. Liệt kê thông tin của các phòng karaoke có mã phòng bắt đầu bằng cụm từ "VIP"
SELECT * 
FROM PHONG 
WHERE MAPHONG like('VIP%')



