CREATE SCHEMA SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT (
    ID	 		INT 		NOT NULL PRIMARY KEY,
	`NAME` 		VARCHAR(50) NOT NULL,
    GENDER		VARCHAR(50),
	CLASS_ID	INT			NOT NULL
);

CREATE TABLE CLASS (
	ID			INT			NOT NULL PRIMARY KEY,
    `NAME`		VARCHAR(50)	NOT NULL,
    TEACHER		VARCHAR(50)	NOT NULL
);

CREATE TABLE RESULT (
	STUDENT_ID	INT			NOT NULL,
    `SUBJECT`	VARCHAR(5)	NOT	NULL,
    SCORE		FLOAT		NOT NULL			
);

ALTER TABLE STUDENT 
ADD CONSTRAINT FK_STUDENT_CLASS
FOREIGN KEY (CLASS_ID)
REFERENCES CLASS(ID);

ALTER TABLE RESULT 
ADD CONSTRAINT FK_RESULT_STUDENT
FOREIGN KEY (STUDENT_ID)
REFERENCES STUDENT(ID);

ALTER TABLE RESULT
ADD CONSTRAINT PK_RESULT
PRIMARY KEY (STUDENT_ID, `SUBJECT`);