CREATE DATABASE JAVA16_FINAL_TEST;
USE JAVA16_FINAL_TEST;


-- 1: Tạo đầy đủ lược đồ cơ sở dữ liệu quan hệ như mô tả ở trên. Sinh viên tự định nghĩa kiểu dữ liệu cho các cột (0.5 điểm)
CREATE TABLE KHACHHANG(
	MAKH VARCHAR(50) PRIMARY KEY,
	TENKH NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(255) NOT NULL,
    SODT VARCHAR(50) NOT NULL,
    MASOTHUE VARCHAR(50) NOT NULL
);

CREATE TABLE MUCTIENGIO(
	MATIENGIO VARCHAR(50) PRIMARY KEY,
    DONGIA INT NOT NULL,
    MOTA NVARCHAR(255)
);

CREATE TABLE PHONG(
	MAPHONG VARCHAR(50) PRIMARY KEY,
    SOKHACHTOIDA INT NOT NULL,
    TRANGTHAI NVARCHAR(100) NOT NULL,
    MOTA NVARCHAR(255)
);

CREATE TABLE DICHVU(
	MADV VARCHAR(50) PRIMARY KEY,
    TENDV VARCHAR(100) NOT NULL,
    DONVITINH VARCHAR(50) NOT NULL,
    DONGIA INT NOT NULL
);

CREATE TABLE HOADON(
	MAHD VARCHAR(50) PRIMARY KEY,
    MAKH VARCHAR(50),
    MAPHONG VARCHAR(50),
    MATIENGIO VARCHAR(50),
    THOIGIANBATDAUSD DATETIME,
    THOIGIANKETTHUCSD DATETIME,
    TRANGTHAIHD NVARCHAR(255),
    
    CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_MAPHONG FOREIGN KEY(MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_MATIENGIO FOREIGN KEY(MATIENGIO) REFERENCES MUCTIENGIO(MATIENGIO)
);

CREATE TABLE CHITIET_SUDUNGDV(
	MAHD VARCHAR(50),
    MADV VARCHAR(50),
    SOLUONG INT,
    
    PRIMARY KEY(MAHD,MADV),
    CONSTRAINT FK_MADV FOREIGN KEY(MADV) REFERENCES DICHVU(MADV), 
    CONSTRAINT FK_MAHD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD)
);


-- 2: Chèn tối thiểu 2 dòng dữ liệu mẫu cho mỗi bảng đã được minh họa ở trên vào tất cả các bảng một cách chính xác (0.5 điểm)
INSERT INTO KHACHHANG VALUES
('KH001','TRAN VAN NAM','HAI CHAU','0905123456','12345678'),
('KH002','NGUYEN MAI ANH','LIEN CHIEU','0905123456','12345679');

INSERT INTO PHONG VALUES
('VIP01',5,'DUOC SU DUNG','PHONG VIP'),
('P02',10,'DUOC SU DUNG','PHONG BINH THUONG');

INSERT INTO DICHVU VALUES
('DV01','HAT DUA','BAO',5000),
('DV02','TRAI CAY','DIA',30000);

INSERT INTO MUCTIENGIO VALUES
('MT01',60000,'AP DUNG TU 6 GIO DEN 17 GIO'),
('MT02',80000,'AP DUNG TU 17 GOI DEN 22 GIO');

INSERT INTO HOADON VALUES
('HD001','KH001','VIP01','MT01','2015-11-20 08:15:00','2015-11-20 12:30:00','DA THANH TOAN'),
('HD002','KH002','P02','MT01','2015-12-12 13:10:00','2015-12-12 17:20:00','CHUA THANH TOAN');

INSERT INTO CHITIET_SUDUNGDV VALUES
('HD001','DV01',5),
('HD002','DV01',8);

SELECT * FROM KHACHHANG;
SELECT * FROM DICHVU;
SELECT * FROM HOADON;
SELECT * FROM PHONG;
SELECT * FROM CHITIET_SUDUNGDV;

-- 3: Liệt kê các phòng karaoke được sử dụng nhiều nhất từ 02.2014 đến 02.2015 (0.5 điểm)
SELECT HD.MAPHONG
FROM HOADON HD JOIN PHONG P ON HD.MAPHONG = P.MAPHONG
WHERE CAST(THOIGIANBATDAUSD AS DATE) BETWEEN STR_TO_DATE('2/2014', '%M%y') AND STR_TO_DATE('2/2015', '%M%y');

-- 4: Liệt kê 2 dịch vụ được sử dụng nhiều nhất trong mỗi tháng từ 01.2014 đến 12.2014 (0.5 điểm) 
SELECT DV.TENDV
FROM CHITIET_SUDUNGDV CS JOIN DICHVU DV ON CS.MADV = DV.MADV JOIN HOADON HD ON CS.MAHD = HD.MAHD
WHERE CAST(THOIGIANBATDAUSD AS DATE) BETWEEN STR_TO_DATE('1/2014', '%M%y') AND STR_TO_DATE('12/2014', '%M%y')
GROUP BY DV.MADV
ORDER BY COUNT(CS.MADV) ASC
LIMIT 2;

-- 5: Liệt kê thông tin của các phòng karaoke có mã phòng bắt đầu bằng cụm từ "VIP" (0.5 điểm)
SELECT * 
FROM HOADON
WHERE MAPHONG LIKE 'VIP%'



