-- 1. STUDENT_ID
-- 2
SELECT S.SNAME, S.GENDER, C.TEACHER
FROM STUDENT S JOIN CLASS C
ON S.CLASS_ID = C.ID;

-- 3
SELECT C.TEACHER, COUNT(*) AS num_students
FROM CLASS C
JOIN STUDENT S 
ON C.ID = S.CLASS_ID
WHERE C.CNAME = '12C'
GROUP BY C.TEACHER;

-- 4
SELECT C.CNAME, COUNT(*) AS num_students
FROM CLASS C
JOIN STUDENT S ON C.ID = S.CLASS_ID
JOIN RESULT R ON S.ID = R.STUDENT_ID
WHERE R.RSUBJECT = 'Math' AND R.SCORE >= 8
   AND EXISTS (
       SELECT 1 FROM Result
       WHERE S.ID = R.student_id
         AND Result.RSUBJECT = 'LITURATURE'
         AND R.SCORE >= 8
   )
GROUP BY C.CNAME;